In [22]:
import numpy as np
import pandas as pd

In [2]:
def f(x):
  return np.exp(x) - np.log(x)

In [3]:
def fd(x):
  return np.exp(x) - (1/x)

In [4]:
x0 = 1.5
eta = 0.01
print(f'x = {x0}, f(x)-{f(x0)}')
for i in range(100):
  x1 = x0 - eta * fd(x0)
  print(f'x = {x1}, f(x)-{f(x1)}')
  x0=x1

x = 1.5, f(x)-4.0762239622299
x = 1.461849775963286, f(x)-3.934229356483592
x = 1.4255511045357447, f(x)-3.805591409611499
x = 1.3909644365935732, f(x)-3.6887266432622425
x = 1.3579664531185673, f(x)-3.582289934909541
x = 1.326447622675889, f(x)-3.4851311153123112
x = 1.2963102006225906, f(x)-3.396260724783285
x = 1.26746657712878, f(x)-3.3148227475707297
x = 1.2398379031800468, f(x)-3.240072718375354
x = 1.213352940004547, f(x)-3.171360004570204
x = 1.1879470894994015, f(x)-3.1081133632342435
x = 1.1635615723707942, f(x)-3.0498290878890386
x = 1.1401427276567169, f(x)-2.996061219089067
x = 1.117641412642213, f(x)-2.94641341175775
x = 1.0960124863141376, f(x)-2.9005321415328984
x = 1.075214362733116, f(x)-2.8581010002490412
x = 1.0552086232422573, f(x)-2.8188358826457147
x = 1.0359596784463254, f(x)-2.7824809064881273
x = 1.0174344725016795, f(x)-2.748804939457108
x = 0.9996022235468174, f(x)-2.717598630564856
x = 0.9824341951444636, f(x)-2.688671863078379
x = 0.9659034944512859, f(x)-

In [4]:
x = np.array([0.2,1.2,1,1.4,-1.5,0.5,-0.5])
y = 3*x + 5

y

array([5.6, 8.6, 8. , 9.2, 0.5, 6.5, 3.5])

In [5]:
w = 0.3
b = 0.1
eta = 0.2

y_pred = w*x+b
y_pred

array([ 0.16,  0.46,  0.4 ,  0.52, -0.35,  0.25, -0.05])

In [6]:
err = y-y_pred
err

array([5.44, 8.14, 7.6 , 8.68, 0.85, 6.25, 3.55])

In [8]:
err_sq = err**2
err_sq

array([29.5936, 66.2596, 57.76  , 75.3424,  0.7225, 39.0625, 12.6025])

In [9]:
err_x = err*x
err_x

array([ 1.088,  9.768,  7.6  , 12.152, -1.275,  3.125, -1.775])

In [11]:
loss = np.mean(err_sq)/2
loss

np.float64(20.095935714285712)

In [13]:
dw = -np.mean(err_x)
dw

np.float64(-4.383285714285714)

In [14]:
db = -np.mean(err)
db

np.float64(-5.7871428571428565)

In [15]:
new_w = w - eta*dw
new_w

np.float64(1.1766571428571428)

In [16]:
new_b = b - eta*db
new_b

np.float64(1.2574285714285713)

In [ ]:
def gd(x, y, w, b,eta=0.2, iter=100):
    all = []
    iter_num=0
    for i in range(iter):
        iter_num +=1
        y_pred = w*x+b
        err = y-y_pred
        err_sq = err**2
        err_x = err*x
        loss = np.mean(err_sq)/2
        dw = -np.mean(err_x)
        db = -np.mean(err)
        new_w = w - eta*dw
        new_b = b - eta*db
        w = new_w
        b = new_b

        all.append([iter_num, w, b, loss, dw, db, new_w, new_b])
        if loss < 0.0001:
            break
    return pd.DataFrame(all, columns=['Iteration Num', 'w', 'b','Loss', 'dw', 'db', 'new_w', 'new_b'])

gd(x,y,w,b)

,Iteration Num,w,b,Loss,dw,db,new_w,new_b
0,1,1.176657,1.257429,20.095936,-4.383286,-5.787143,1.176657,1.257429
1,2,1.797164,2.125763,10.952998,-3.102536,-4.341670,1.797164,2.125763
2,3,2.233140,2.779654,6.009612,-2.179876,-3.269455,2.233140,2.779654
3,4,2.536583,3.274116,3.326445,-1.517218,-2.472315,2.536583,3.274116
4,5,2.745197,3.649746,1.862422,-1.043071,-1.878149,2.745197,3.649746
5,6,2.886272,3.936541,1.057980,-0.705373,-1.433975,2.886272,3.936541
6,7,2.979519,4.156707,0.611854,-0.466237,-1.100827,2.979519,4.156707
7,8,3.039143,4.326711,0.361462,-0.298119,-0.850023,3.039143,4.326711
8,9,3.075347,4.458797,0.218786,-0.181018,-0.660428,3.075347,4.458797
9,10,3.095433,4.562086,0.135968,-0.100432,-0.516447,3.095433,4.562086


2 features

In [34]:
x1 = np.linspace(-0.6, 0.7, 10)
x2 = np.linspace(-0.9, 0.92, 10)
y = 5 + 8*x1 + 9*x2

eta = 0.2
w1, w2, b = 0.3, 0.1, -0.3

In [36]:
def gd(x1, x2, y, w1, w2, b,eta=0.2, iter=100):
    all = []
    iter_num=0
    for i in range(iter):
        iter_num +=1
        y_pred = w1*x1 + w2*x2 + b
        err = y-y_pred
        err_sq = err**2
        err_x1 = err*x1
        err_x2 = err*x2
        loss = np.mean(err_sq)/2
        dw1 = -np.mean(err_x1)
        dw2 = -np.mean(err_x2)
        db = -np.mean(err)
        new_w1 = w1 - eta*dw1
        new_w2 = w2 - eta*dw2
        new_b = b - eta*db
        w1 = new_w1
        w2 = new_w2
        b = new_b
        all.append([iter_num, w1, w2, b, loss, dw1, dw2, db, new_w1, new_w2, new_b])
        if loss < 0.0001:
            break
    return pd.DataFrame(all, columns=['Iteration Num', 'w1', 'w2', 'b','Loss', 'dw1','dw2', 'db', 'new_w1','new_w2', 'new_b'])

gd(x1,x2,y,w1, w2,b)

,Iteration Num,w1,w2,b,Loss,dw1,dw2,db,new_w1,new_w2,new_b
0,1,1.051767,1.083185,0.854800,51.648482,-3.758833,-4.915927,-5.774000,1.051767,1.083185,0.854800
1,2,1.718245,1.961394,1.769156,38.434118,-3.332392,-4.391041,-4.571780,1.718245,1.961394,1.769156
2,3,2.309888,2.746310,2.492220,28.943456,-2.958216,-3.924583,-3.615318,2.309888,2.746310,2.492220
3,4,2.835728,3.448229,3.063184,22.033811,-2.629201,-3.509593,-2.854823,2.835728,3.448229,3.063184
4,5,3.303594,4.076233,3.513294,16.936249,-2.339326,-3.140023,-2.250547,3.303594,4.076233,3.513294
...,...,...,...,...,...,...,...,...,...,...,...
56,57,7.247615,9.506651,5.033495,0.000198,-0.008200,-0.011543,0.001046,7.247615,9.506651,5.033495
57,58,7.249088,9.508725,5.033306,0.000160,-0.007367,-0.010370,0.000942,7.249088,9.508725,5.033306
58,59,7.250412,9.510589,5.033137,0.000129,-0.006618,-0.009317,0.000848,7.250412,9.510589,5.033137
59,60,7.251601,9.512263,5.032984,0.000104,-0.005946,-0.008370,0.000763,7.251601,9.512263,5.032984


Stochastic Gradient Descent

In [46]:
x = np.array([0.2,1.2,1,1.4,-1.5,0.5,-0.5])
y = 3*x + 5

w = 0.3
b = 0.1
eta = 0.2
tol = 0.0001
n = len(x)

In [47]:
for i in range(0,50):
    for j in range(0, len(x)):
        y_pred = w*x[j] +b
        err = y[j] - y_pred
        dw, db = -(err*x[j]), -(err)
        new_w, new_b = w - eta* dw, b - eta*db
        w,b = new_w, new_b
    y_pred_all = w*x + b
    err_all = y-y_pred_all
    L = np.sum(err_all**2)/(2*n)
    print("w = ", w, ", b=", b)
    print("Loss = ", L)
    if L < tol:
        print(f'Algo stopped at {i+1}th iteration as Loss < Tolerance {tol}')
        break

w =  2.8344904011609597 , b= 4.37409141363968
Loss =  0.2439872496626577
w =  2.999644499916011 , b= 4.894869035610247
Loss =  0.005538604792553377
w =  3.003120495925965 , b= 4.978489237403861
Loss =  0.00021430224311760386
w =  3.0010085087073324 , b= 4.995150461760576
Loss =  1.0674381186758593e-05
Algo stopped at 4th iteration as Loss < Tolerance 0.0001


Mini-Batch GD

In [53]:
x = np.array([0.2,1.2,1,1.4,-1.5,0.5,-0.5])
y = 3*x + 5

w = 0.3
b = 0.1
batches = [[0,6], [3,1,5],[4,2]]
tol = 0.0001

In [54]:
for i in range(0,50):
    for j in range(0, len(x)):
        for batch in batches:
            y_pred = w*x[batch] +b
            err = y[batch] - y_pred
            dw, db = -np.sum(err*x[batch])/len(batch), -np.sum(err)/len(batch)
            new_w, new_b = w - eta* dw, b - eta*db
            w,b = new_w, new_b
    y_pred_all = w*x + b
    err_all = y-y_pred_all
    L = np.sum(err_all**2)/(2*n)
    print("w = ", w, ", b=", b)
    print("Loss = ", L)
    if L < tol:
        print(f'Algo stopped at {i+1}th iteration as Loss < Tolerance {tol}')
        break
    

w =  3.0079424602735796 , b= 4.972191579612213
Loss =  0.00034648090604227834
w =  3.000284231813902 , b= 4.999566868938669
Loss =  9.484121890159695e-08
Algo stopped at 2th iteration as Loss < Tolerance 0.0001
