In [5]:
import numpy as np
array = np.arange(1,28)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [6]:
array_3d = array.reshape(3,3,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [7]:
#Create a 3×3 array of all True Boolean values

mask = array_3d>0
print (mask)
array_3d[mask]

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [8]:
#Extract odd numbers from an array
mask_odd = array_3d %2 == 1
array_3d[mask_odd]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27])

In [9]:
#Replace all odd numbers with -1
array_3d[mask_odd] = -1
array_3d

array([[[-1,  2, -1],
        [ 4, -1,  6],
        [-1,  8, -1]],

       [[10, -1, 12],
        [-1, 14, -1],
        [16, -1, 18]],

       [[-1, 20, -1],
        [22, -1, 24],
        [-1, 26, -1]]])

In [10]:
array = np.arange(1,17)
array_2d = array.reshape(4,4)
array_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
#Reverse columns of a 2D array
array_2d[::,::-1]


array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [12]:
#Get indices of elements greater than 5 [hint: check where method of numpy]
mask_more_then_5 = array_2d > 5
array_2d[mask_more_then_5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [47]:
#Access last row - last column
# ele = array_2d[-1]
# ele
shapeOf = np.shape(array_2d)
print (shapeOf)
ele = array_2d[shapeOf[0]-1, shapeOf[1]-1]
ele

(4, 4)


16

In [14]:
# set 2

In [15]:
array_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
#Normalize a NumPy array [ to normalize means scaling the values of an array into a specific range, often [0, 1]]

newArr = array_2d/np.max(array_2d)
newArr

array([[0.0625, 0.125 , 0.1875, 0.25  ],
       [0.3125, 0.375 , 0.4375, 0.5   ],
       [0.5625, 0.625 , 0.6875, 0.75  ],
       [0.8125, 0.875 , 0.9375, 1.    ]])

In [17]:
zeroArray = np.zeros((4,4))
zeroArray

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
#Create a 5×5 array with 1 on border and 0 inside
zeroArray[0] = 1
zeroArray[len(zeroArray)-1] = 1
TzeroArray=np.transpose(zeroArray)

TzeroArray[0] = 1
TzeroArray[len(TzeroArray)-1] = 1
TzeroArray



array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [19]:
#Create a random array of 10×10: perform stats (min, max, mean, std)
arr = np.random.randint(1,100,100).reshape(10,10)
arr

array([[32, 68, 48, 21, 38,  6,  2, 13,  8, 94],
       [44, 47, 35, 81, 52, 63, 67, 70, 46, 32],
       [79, 52,  6, 95, 41, 39, 77,  7,  3, 80],
       [56, 98, 45, 59, 64, 16, 36, 42, 64, 20],
       [23, 13, 12, 80, 35, 65, 70, 72, 91, 96],
       [91, 36, 66, 70,  7, 97, 55, 68, 69, 40],
       [71, 54, 27, 46, 68, 59, 56, 14, 15, 38],
       [40, 26, 82, 18, 41, 38, 63, 48, 94,  2],
       [54, 60, 36, 59, 41, 54, 64, 67, 44, 59],
       [14, 93,  6, 80, 98, 20, 42, 13, 64, 94]])

In [20]:
np.min(arr, axis=0)

array([14, 13,  6, 18,  7,  6,  2,  7,  3,  2])

In [21]:
np.min(arr, axis=1)

array([ 2, 32,  3, 16, 12,  7, 14,  2, 36,  6])

In [22]:
np.max(arr, axis=0)

array([91, 98, 82, 95, 98, 97, 77, 72, 94, 96])

In [23]:
np.max(arr, axis=1)

array([94, 81, 95, 98, 96, 97, 71, 94, 67, 98])

In [24]:
np.mean(arr, axis=0)

array([50.4, 54.7, 36.3, 60.9, 48.5, 45.7, 53.2, 41.4, 49.8, 55.5])

In [25]:
np.mean(arr, axis=1)

array([33. , 53.7, 47.9, 50. , 55.7, 59.9, 44.8, 45.2, 53.8, 52.4])

In [26]:
np.std(arr, axis=0)

array([23.44866734, 25.5462326 , 23.87069333, 24.57824241, 22.94885618,
       26.02325883, 20.74993976, 25.90057914, 31.01548001, 32.30866757])

In [27]:
np.std(arr, axis=1)

array([28.38309356, 15.15288751, 32.63571663, 22.70242278, 30.41068891,
       25.33949486, 19.58979326, 26.7050557 ,  9.73447482, 35.62639471])

In [28]:
#Broadcast a 1D array over a 2D array [all possible scenarios]
arr_1d = np.arange(1,5)
arr_1d

array([1, 2, 3, 4])

In [29]:
arr_2d = np.arange(1,17).reshape(4,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [30]:
mulArray = arr_2d * arr_1d
mulArray

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32],
       [ 9, 20, 33, 48],
       [13, 28, 45, 64]])

In [31]:
mulArray = arr_1d * arr_2d 
mulArray

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32],
       [ 9, 20, 33, 48],
       [13, 28, 45, 64]])

In [32]:
arr_1d = np.arange(1,5).reshape(4,1)
arr_1d

array([[1],
       [2],
       [3],
       [4]])

In [33]:
mulArray = arr_1d * arr_2d 
mulArray

array([[ 1,  2,  3,  4],
       [10, 12, 14, 16],
       [27, 30, 33, 36],
       [52, 56, 60, 64]])

In [34]:
# arr = np.array([3, 1, 4, 2])
# indices = np.argsort(arr)

# print("Original array:", arr)
# print("Sorted indices:", indices)
# print("Sorted array using indices:", arr[indices])
sorted=arr[1,:].argsort()
sorted



array([9, 2, 0, 8, 1, 4, 5, 6, 7, 3], dtype=int64)

In [35]:
arr[sorted]

array([[14, 93,  6, 80, 98, 20, 42, 13, 64, 94],
       [79, 52,  6, 95, 41, 39, 77,  7,  3, 80],
       [32, 68, 48, 21, 38,  6,  2, 13,  8, 94],
       [54, 60, 36, 59, 41, 54, 64, 67, 44, 59],
       [44, 47, 35, 81, 52, 63, 67, 70, 46, 32],
       [23, 13, 12, 80, 35, 65, 70, 72, 91, 96],
       [91, 36, 66, 70,  7, 97, 55, 68, 69, 40],
       [71, 54, 27, 46, 68, 59, 56, 14, 15, 38],
       [40, 26, 82, 18, 41, 38, 63, 48, 94,  2],
       [56, 98, 45, 59, 64, 16, 36, 42, 64, 20]])

In [36]:
#Set 3

In [37]:
#Find common elements between two arrays [with and without using intersect1d]
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,8])
mask = np.isin(arr1, arr2)  
arr3 = arr1[mask]  
arr3

array([4, 5])

In [38]:
# Subtract row mean from each row of a 2D array
array = np.arange(1,17)
array_2d = array.reshape(4,4)
print(array_2d)
print(np.mean(array_2d, axis=1))

array_2d = array_2d[:,:] - np.mean(array_2d, axis=1)
array_2d


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 2.5  6.5 10.5 14.5]


array([[ -1.5,  -4.5,  -7.5, -10.5],
       [  2.5,  -0.5,  -3.5,  -6.5],
       [  6.5,   3.5,   0.5,  -2.5],
       [ 10.5,   7.5,   4.5,   1.5]])

In [39]:
#Given a 4×4 array, swap the first half rows with the second half rows
array = np.arange(1,17)
array_2d = array.reshape(4,4)
first = array_2d[:2, :]
second = array_2d[2:,:]
print (first)
print (second)
ans = np.vstack([second, first])
ans

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [40]:
#Given a 1D array of random numbers, find the indices of the 5 largest values (no sorting/ check argsort() instead).
arr = np.random.randint(1,100,10)
arr

array([ 7, 29, 93, 62, 34, 19, 20, 97, 19,  9])

In [41]:
mask = arr.argsort()
print (mask)
arr = arr[mask][len(arr)-5:]
# mask = mask[len(arr)-5:]
print (arr)


[0 9 5 8 6 1 4 3 2 7]
[29 34 62 93 97]


In [42]:
#From a 2D NumPy array, extract only the unique rows (no duplicates hint: check unique method).
duplicate = np.vstack([array_2d, array_2d])
duplicate

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
unique = np.unique(duplicate, axis = 0)

In [44]:
unique

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])