In [3]:
import numpy as np
arr_1d=np.arange(1,11)
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr_1d[4]

5

In [5]:
arr_1d[-4]

7

In [6]:
arr_1d[4:8]

array([5, 6, 7, 8])

In [7]:
arr_1d[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
arr_1d[4:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr_1d[:8:2]

array([1, 3, 5, 7])

In [10]:
arr_1d[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [11]:
mask= arr_1d > 5
mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [12]:
arr_1d[mask]

array([ 6,  7,  8,  9, 10])

In [ ]:
1