In [9]:
import numpy as np

In [ ]:
'''Create numpy array

array(list/tuple)
arange(start,end)
random.random((row,col))
random.randint(low,high,size)
random.uniform(low,high,size)
linespace(low,high,size)
'''

In [ ]:
'''numpy properties
reshape()
size
a'''

In [26]:
arr=np.array([1,2,3,4,5,6])
arr


array([1, 2, 3, 4, 5, 6])

In [27]:
arr.shape

(6,)

In [29]:
arr.reshape(2,3).ndim

2

In [21]:
arr.dtype

dtype('<U11')

In [30]:
arr_2d = np.array([[1,2,3], [4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr1.reshape(3,3).astype(float)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [38]:
arr2 = np.array([1,2,3,4], dtype=float, ndmin=4)
arr2

array([[[[1., 2., 3., 4.]]]])

In [39]:
random_a = np.random.randint(10, 40, 10)
random_a


array([20, 14, 19, 13, 35, 29, 37, 38, 39, 15])

In [40]:
random_u = np.random.uniform(10, 40, 10)
random_u

array([27.26269827, 29.70705065, 30.74688747, 37.19350831, 13.99672495,
       31.92887993, 16.36608705, 27.7463577 , 36.73452923, 35.34438211])

In [42]:
random_l = np.linspace(10, 40, 10)
random_l


array([10.        , 13.33333333, 16.66666667, 20.        , 23.33333333,
       26.66666667, 30.        , 33.33333333, 36.66666667, 40.        ])

In [55]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
empty = np.empty((3,3))
empty

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [57]:
identy_m = np.identity(3)
identy_m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
empty_a = np.empty((4,5))
empty_a

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        8.90096090e-307, 4.45042952e-307],
       [3.33772792e-307, 2.11393560e-307, 1.42418987e-306,
        1.37961641e-306, 1.60220528e-306],
       [1.24611266e-306, 9.34598925e-307, 1.24612081e-306,
        1.11260755e-306, 1.60220393e-306],
       [1.51320640e-306, 9.34609790e-307, 1.86921279e-306,
        1.24610723e-306, 1.16493489e-311]])

In [61]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
arr=np.transpose(arr)
arr

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [67]:
arr1= np.random.randint(10,20,12).reshape(4,3)
arr1

array([[18, 16, 11],
       [13, 18, 13],
       [15, 12, 14],
       [18, 14, 15]])

In [68]:
horizaltal = np.hstack((arr,arr1))
horizaltal

array([[ 0,  4,  8, 18, 16, 11],
       [ 1,  5,  9, 13, 18, 13],
       [ 2,  6, 10, 15, 12, 14],
       [ 3,  7, 11, 18, 14, 15]])

In [69]:
verticle = np.vstack((arr,arr1))
verticle

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [18, 16, 11],
       [13, 18, 13],
       [15, 12, 14],
       [18, 14, 15]])

In [70]:
sort_a = np.sort(arr1, axis=1)
sort_a


array([[11, 16, 18],
       [13, 13, 18],
       [12, 14, 15],
       [14, 15, 18]])

In [71]:
sort_a = np.sort(arr1, axis=0)
sort_a

array([[13, 12, 11],
       [15, 14, 13],
       [18, 16, 14],
       [18, 18, 15]])

In [72]:
raveled = np.ravel(verticle)
raveled

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11, 18, 16, 11, 13, 18,
       13, 15, 12, 14, 18, 14, 15])

In [75]:
combined = np.concatenate((arr,arr1))
combined

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [18, 16, 11],
       [13, 18, 13],
       [15, 12, 14],
       [18, 14, 15]])