In [18]:
import numpy as np

In [19]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
arr = arr.reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
min_in_array = np.min(arr, axis = 0) 
print (min_in_array)
min_in_array1 = np.min(arr, axis = 1) 
min_in_array1



[1 2 3]


array([ 1,  4,  7, 10])

In [22]:
max_in_array = np.max(arr, axis = 0) 
max_in_array



array([10, 11, 12])

In [23]:
max_in_array1 = np.max(arr, axis = 1) 
max_in_array1

array([ 3,  6,  9, 12])

In [24]:
sumArray = np.sum(arr, axis = 1)
sumArray

array([ 6, 15, 24, 33])

In [25]:
sumArray = np.sum(arr, axis = 0)
sumArray

array([22, 26, 30])

In [26]:
prodArray = np.prod(arr, axis = 0)
prodArray

array([ 280,  880, 1944])

In [27]:
prodArray = np.prod(arr, axis = 1)
prodArray

array([   6,  120,  504, 1320])

In [28]:
averageArray = np.average(arr, axis = 0)
averageArray

array([5.5, 6.5, 7.5])

In [30]:
stdDev = np.std(arr, axis = 1)
stdDev

array([0.81649658, 0.81649658, 0.81649658, 0.81649658])

In [32]:
cosArray = np.cos(arr)
cosArray

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396]])

In [38]:
cosArray = np.cos(np.sum(arr, axis = 1))
cosArray

array([ 0.96017029, -0.75968791,  0.42417901, -0.01327675])

In [42]:
powerArray = np.power(arr, 1)
powerArray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)

In [43]:
cumSum = np.cumsum(arr)
cumSum

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78])

In [44]:
logArray = np.log(arr)
logArray

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665]])

In [45]:
root = np.sqrt(arr)
root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [46]:
ceilArray = np.ceil(root)
ceilArray

array([[1., 2., 2.],
       [2., 3., 3.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [48]:
floorArray = np.floor(root)
floorArray

array([[1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 3.],
       [3., 3., 3.]])

In [51]:
arr


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
percentileArray = np.percentile(arr, 40)
percentileArray

5.4

In [54]:
def square(n):
    return n * n
sq_fun = np.vectorize(square)
sq_fun

In [56]:
squareArray = sq_fun(arr)


array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [ ]:
oneZeroArray = np.