In [1]:
import numpy as np


In [13]:
arr_1d = np.array([1,2,3,4,5,6])

In [14]:
arr_1d + 5

array([ 6,  7,  8,  9, 10, 11])

In [15]:
arr_1d < 5

array([ True,  True,  True,  True, False, False])

In [16]:
arr_1d= arr_1d -5 
arr_1d

array([-4, -3, -2, -1,  0,  1])

In [17]:
arr_1d= arr_1d +5 
arr_1d

array([1, 2, 3, 4, 5, 6])

In [18]:
arr_2d = np.arange(12).reshape(2,6)
arr_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
arr_1d + arr_2d

array([[ 1,  3,  5,  7,  9, 11],
       [ 7,  9, 11, 13, 15, 17]])

In [21]:
arr = np.arange(10,12).reshape(2,1)
arr

array([[10],
       [11]])

In [22]:
arr * arr_2d

array([[  0,  10,  20,  30,  40,  50],
       [ 66,  77,  88,  99, 110, 121]])

In [20]:
print("helo")

helo
